package com.amg.exchange.remittance.model;


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.amg.exchange.common.model.CompanyMaster;
import com.amg.exchange.common.model.CountryMaster;

/**
* ExApplicationAmlCheck generated by hbm2java
*/
@Entity
@Table(name = "EX_APPLICATION_AML_CHECK")
public class ApplicationAmlCheck implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal applicationAmlCheckId;
	private CompanyMaster fsCompanyMaster;
	private CountryMaster fsCountryMaster;
	private String blockReason;
	private String blockClear;
	private String blockRemittance;
	private Date blockDate;
	private String blockUser;
	private String blockCustomer;
	private String customerSignature;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;
	private String isactive;

	public ApplicationAmlCheck() {
	}

	public ApplicationAmlCheck(BigDecimal applicationAmlCheckId) {
		this.applicationAmlCheckId = applicationAmlCheckId;
	}

	public ApplicationAmlCheck(BigDecimal applicationAmlCheckId,
			CompanyMaster fsCompanyMaster, CountryMaster fsCountryMaster,
			String blockReason, String blockClear, String blockRemittance,
			Date blockDate, String blockUser, String blockCustomer,
			String customerSignature, Date createdDate, String createdBy,
			Date modifiedDate, String modifiedBy, String isactive) {
		this.applicationAmlCheckId = applicationAmlCheckId;
		this.fsCompanyMaster = fsCompanyMaster;
		this.fsCountryMaster = fsCountryMaster;
		this.blockReason = blockReason;
		this.blockClear = blockClear;
		this.blockRemittance = blockRemittance;
		this.blockDate = blockDate;
		this.blockUser = blockUser;
		this.blockCustomer = blockCustomer;
		this.customerSignature = customerSignature;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
		this.isactive = isactive;
	}

	@Id
	@GeneratedValue(generator="ex_application_aml_check_seq",strategy=GenerationType.SEQUENCE)
	@SequenceGenerator(name="ex_application_aml_check_seq",sequenceName="EX_APPLICATION_AML_CHECK_SEQ",allocationSize=1)
	@Column(name = "APPLICATION_AML_CHECK_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getApplicationAmlCheckId() {
		return this.applicationAmlCheckId;
	}

	public void setApplicationAmlCheckId(BigDecimal applicationAmlCheckId) {
		this.applicationAmlCheckId = applicationAmlCheckId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANY_ID")
	public CompanyMaster getFsCompanyMaster() {
		return this.fsCompanyMaster;
	}

	public void setFsCompanyMaster(CompanyMaster fsCompanyMaster) {
		this.fsCompanyMaster = fsCompanyMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "APPLICATION_COUNTRY_ID")
	public CountryMaster getFsCountryMaster() {
		return this.fsCountryMaster;
	}

	public void setFsCountryMaster(CountryMaster fsCountryMaster) {
		this.fsCountryMaster = fsCountryMaster;
	}

	@Column(name = "BLOCK_REASON", length = 100)
	public String getBlockReason() {
		return this.blockReason;
	}

	public void setBlockReason(String blockReason) {
		this.blockReason = blockReason;
	}

	@Column(name = "BLOCK_CLEAR", length = 1)
	public String getBlockClear() {
		return this.blockClear;
	}

	public void setBlockClear(String blockClear) {
		this.blockClear = blockClear;
	}

	@Column(name = "BLOCK_REMITTANCE", length = 60)
	public String getBlockRemittance() {
		return this.blockRemittance;
	}

	public void setBlockRemittance(String blockRemittance) {
		this.blockRemittance = blockRemittance;
	}

	
	@Column(name = "BLOCK_DATE", length = 7)
	public Date getBlockDate() {
		return this.blockDate;
	}

	public void setBlockDate(Date blockDate) {
		this.blockDate = blockDate;
	}

	@Column(name = "BLOCK_USER", length = 60)
	public String getBlockUser() {
		return this.blockUser;
	}

	public void setBlockUser(String blockUser) {
		this.blockUser = blockUser;
	}

	@Column(name = "BLOCK_CUSTOMER", length = 60)
	public String getBlockCustomer() {
		return this.blockCustomer;
	}

	public void setBlockCustomer(String blockCustomer) {
		this.blockCustomer = blockCustomer;
	}

	@Column(name = "CUSTOMER_SIGNATURE", length = 4000)
	public String getCustomerSignature() {
		return this.customerSignature;
	}

	public void setCustomerSignature(String customerSignature) {
		this.customerSignature = customerSignature;
	}

	
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", length = 15)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	
	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "MODIFIED_BY", length = 15)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "ISACTIVE", length = 1)
	public String getIsactive() {
		return this.isactive;
	}

	public void setIsactive(String isactive) {
		this.isactive = isactive;
	}

}
