package com.amg.exchange.treasury.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

	/**
	 * Nazish Hashmi
	 */
	@Entity
	@Table(name = "EX_TICKETS")
	public class Tickets implements Serializable {

		/**
		 * 
		 */
		private static final long serialVersionUID = 1L;
		private BigDecimal ticketsId;
		private String dealid;
		private short processed;
		private String processedby;
		private Date processedat;
		private Short processed2;
		private String processed2by;
		private Date processed2at;
		private String lastmodifiedby;
		private Date lastmodifiedat;
		private String localtcid;
		private String sourcereference;
		private Date timeofdeal;
		private String dealerid;
		private Long puredealtype;
		private Short dealtype;
		private String bank1dealingcode;
		private String brokerdealingcode;
		private String currency1;
		private String currency2;
		private BigDecimal dealvolumecurrency1;
		private BigDecimal exchangerateperiod1;
		private BigDecimal exchangerateperiod2;
		private Short methodofdeal;
		private Long period1;
		private Long period2;
		private Date confirmationtime;
		private String confirmedbyid;
		private String basecurrency;
		private String bank1name;
		private BigDecimal depositrate;
		private BigDecimal swaprate;
		private Short sourceofdata;
		private Short ratedirection;
		private Date valuedateperiod1currency1;
		private Date valuedateperiod1currency2;
		private Date valuedateperiod2currency1;
		private Date valuedateperiod2currency2;
		private String dealername;
		private String reviewreferencenumber;
		private String brokername;
		private Date frafixingdate;
		private Date frasettlementdate;
		private Date framaturitydate;
		private Short immindicator;
		private BigDecimal outrightpointspremiumrate;
		private BigDecimal spotbasisrate;
		private Clob conversationtext;
		private String paymentinstructionp1c1;
		private String paymentinstructionp1c2;
		private String paymentinstructionp2c1;
		private String paymentinstructionp2c2;
		private String secondarysourceref;
		private BigDecimal ratec1usd;
		private BigDecimal ratec2usd;
		private BigDecimal ratebasecusd;
		private BigDecimal calvolumep1c2;
		private BigDecimal calvolumep2c2;
		private BigDecimal calvolumep2c1;
		private String confirmedbyname;
		private String commenttext;
		private String userdefinedtitle1;
		private String userdefineddata1;
		private String userdefinedtitle2;
		private String userdefineddata2;
		private String userdefinedtitle3;
		private String userdefineddata3;
		private String idifcontra;
		private String idprevious;
		private BigDecimal interestvolume;
		private Long elapseddays;
		private Long yearlength;
		private Long priceconvention;
		private String swiftbicc1p1;
		private String swiftbicc1p2;
		private String swiftbicc2p1;
		private String swiftbicc2p2;
		private BigDecimal creditreduction;
		private BigDecimal creditremaining;
		private String basecurrency2;
		private String basecurrency3;
		private BigDecimal ratebasec2usd;
		private BigDecimal ratebasec3usd;
		private Long scope;
		private String customdealingfield1;
		private String customdealingfield2;
		private String customdealingfield3;
		private String midofficecomment;
		private Short autogeneratedticket;
		private String transactionid;
		private Date startdate;
		private Date enddate;
		private Date deliverydate;
		private Date deliverydate2;
		private Date expirydate;
		private Date expirydate2;
		private Date paymentdate;
		private Date premiumdate;
		private String interestdaybasis;
		private String interestdaybasis2;
		private String index1;
		private String index2;
		private Short resetfrequency;
		private Byte resetbusinessdayconvention;
		private Byte paymentbusinessdayconvention;
		private String resetcalendar;
		private Short paymentfrequency;
		private Short secondaryfrequency;
		private String stubindicator;
		private BigDecimal stubrate;
		private BigDecimal indexspread;
		private String optiontype;
		private String optiontype2;
		private String cutoff;
		private String cutoff2;
		private Byte expirystyle;
		private Byte direction2;
		private Byte tradingstrategy;
		private Byte settlement;
		private BigDecimal premiumamount;
		private BigDecimal premiumamount2;
		private BigDecimal volatility;
		private BigDecimal volatility2;
		private BigDecimal premiumquote;
		private BigDecimal premiumquote2;
		private String premiumcurrency;
		private BigDecimal totalnetpremiumamount;
		private Byte premiumquoteconvention;
		private Byte hedgedirection;
		private Byte hedgedirection2;
		private Date hedgevaluedate;
		private Date hedgevaluedate2;
		private BigDecimal hedgeamount;
		private BigDecimal hedgeamount2;
		private BigDecimal hedgecontraamount;
		private BigDecimal hedgecontraamount2;
		private BigDecimal hedgerate;
		private BigDecimal hedgerate2;
		private BigDecimal depositratereference;
		private BigDecimal depositratereference2;
		private BigDecimal swappointsreference;
		private BigDecimal swappointsreference2;
		private BigDecimal fixedrate;
		private String bank2name;
		private String customdealingfield4;
		private String customdealingfield5;
		private String customdealingfield6;
		private String clearinghouse;
		private String ourclearingmember;
		private String theirclearingmember;
		private String onbehalfofname;
		private String onbehalfofcode;
		private Date premiumdate2;
		private String clearingaccount;
		private BigDecimal bestbid;
		private BigDecimal bestask;
		private String ourlei;
		private String theirlei;
		private BigDecimal brokerageamount;
		private String brokeragecurrency;
		private String reportingparty;
		private String namespace;
		private String linkid;
		private String transactionid2;
		private String transactionid3;
		private String transactionid4;
		private String transactionidhedge1;
		private String transactionidhedge2;
		private String traderepository;
		private BigDecimal midprice;
		private String ourbiccode;
		private String theirbiccode;
		private String executionfacility;
		private BigDecimal midmarketspotrate;
		private BigDecimal midmarketnearrate;
		private BigDecimal midmarketfarrate;
		private BigDecimal midmarketswaprate;
		private Short blocktrade;
		private Short clearingeligible;
		private Short ourclearexemp;
		private Short theirclearexemp;
		private Short weareusperson;
		private Short theyareusperson;
		private String ourreportjurisd;
		private String theirreportjurisd;
		private String transactionidhedge3;
		private String transactionidhedge4;
		private String cpuserid;
		private String cpusername;
		private String theirclearingaccount;
		private String uniqueproductid;

		public Tickets() {
		}

		public Tickets(BigDecimal ticketsId, short processed,
				String sourcereference, Date timeofdeal) {
			this.ticketsId = ticketsId;
			this.processed = processed;
			this.sourcereference = sourcereference;
			this.timeofdeal = timeofdeal;
		}

		public Tickets(BigDecimal ticketsId, String dealid, short processed,
				String processedby, Date processedat, Short processed2,
				String processed2by, Date processed2at, String lastmodifiedby,
				Date lastmodifiedat, String localtcid, String sourcereference,
				Date timeofdeal, String dealerid, Long puredealtype,
				Short dealtype, String bank1dealingcode, String brokerdealingcode,
				String currency1, String currency2, BigDecimal dealvolumecurrency1,
				BigDecimal exchangerateperiod1, BigDecimal exchangerateperiod2,
				Short methodofdeal, Long period1, Long period2,
				Date confirmationtime, String confirmedbyid, String basecurrency,
				String bank1name, BigDecimal depositrate, BigDecimal swaprate,
				Short sourceofdata, Short ratedirection,
				Date valuedateperiod1currency1, Date valuedateperiod1currency2,
				Date valuedateperiod2currency1, Date valuedateperiod2currency2,
				String dealername, String reviewreferencenumber, String brokername,
				Date frafixingdate, Date frasettlementdate, Date framaturitydate,
				Short immindicator, BigDecimal outrightpointspremiumrate,
				BigDecimal spotbasisrate, Clob conversationtext,
				String paymentinstructionp1c1, String paymentinstructionp1c2,
				String paymentinstructionp2c1, String paymentinstructionp2c2,
				String secondarysourceref, BigDecimal ratec1usd,
				BigDecimal ratec2usd, BigDecimal ratebasecusd,
				BigDecimal calvolumep1c2, BigDecimal calvolumep2c2,
				BigDecimal calvolumep2c1, String confirmedbyname,
				String commenttext, String userdefinedtitle1,
				String userdefineddata1, String userdefinedtitle2,
				String userdefineddata2, String userdefinedtitle3,
				String userdefineddata3, String idifcontra, String idprevious,
				BigDecimal interestvolume, Long elapseddays, Long yearlength,
				Long priceconvention, String swiftbicc1p1, String swiftbicc1p2,
				String swiftbicc2p1, String swiftbicc2p2,
				BigDecimal creditreduction, BigDecimal creditremaining,
				String basecurrency2, String basecurrency3,
				BigDecimal ratebasec2usd, BigDecimal ratebasec3usd, Long scope,
				String customdealingfield1, String customdealingfield2,
				String customdealingfield3, String midofficecomment,
				Short autogeneratedticket, String transactionid, Date startdate,
				Date enddate, Date deliverydate, Date deliverydate2,
				Date expirydate, Date expirydate2, Date paymentdate,
				Date premiumdate, String interestdaybasis,
				String interestdaybasis2, String index1, String index2,
				Short resetfrequency, Byte resetbusinessdayconvention,
				Byte paymentbusinessdayconvention, String resetcalendar,
				Short paymentfrequency, Short secondaryfrequency,
				String stubindicator, BigDecimal stubrate, BigDecimal indexspread,
				String optiontype, String optiontype2, String cutoff,
				String cutoff2, Byte expirystyle, Byte direction2,
				Byte tradingstrategy, Byte settlement, BigDecimal premiumamount,
				BigDecimal premiumamount2, BigDecimal volatility,
				BigDecimal volatility2, BigDecimal premiumquote,
				BigDecimal premiumquote2, String premiumcurrency,
				BigDecimal totalnetpremiumamount, Byte premiumquoteconvention,
				Byte hedgedirection, Byte hedgedirection2, Date hedgevaluedate,
				Date hedgevaluedate2, BigDecimal hedgeamount,
				BigDecimal hedgeamount2, BigDecimal hedgecontraamount,
				BigDecimal hedgecontraamount2, BigDecimal hedgerate,
				BigDecimal hedgerate2, BigDecimal depositratereference,
				BigDecimal depositratereference2, BigDecimal swappointsreference,
				BigDecimal swappointsreference2, BigDecimal fixedrate,
				String bank2name, String customdealingfield4,
				String customdealingfield5, String customdealingfield6,
				String clearinghouse, String ourclearingmember,
				String theirclearingmember, String onbehalfofname,
				String onbehalfofcode, Date premiumdate2, String clearingaccount,
				BigDecimal bestbid, BigDecimal bestask, String ourlei,
				String theirlei, BigDecimal brokerageamount,
				String brokeragecurrency, String reportingparty, String namespace,
				String linkid, String transactionid2, String transactionid3,
				String transactionid4, String transactionidhedge1,
				String transactionidhedge2, String traderepository,
				BigDecimal midprice, String ourbiccode, String theirbiccode,
				String executionfacility, BigDecimal midmarketspotrate,
				BigDecimal midmarketnearrate, BigDecimal midmarketfarrate,
				BigDecimal midmarketswaprate, Short blocktrade,
				Short clearingeligible, Short ourclearexemp, Short theirclearexemp,
				Short weareusperson, Short theyareusperson, String ourreportjurisd,
				String theirreportjurisd, String transactionidhedge3,
				String transactionidhedge4, String cpuserid, String cpusername,
				String theirclearingaccount, String uniqueproductid) {
			this.ticketsId = ticketsId;
			this.dealid = dealid;
			this.processed = processed;
			this.processedby = processedby;
			this.processedat = processedat;
			this.processed2 = processed2;
			this.processed2by = processed2by;
			this.processed2at = processed2at;
			this.lastmodifiedby = lastmodifiedby;
			this.lastmodifiedat = lastmodifiedat;
			this.localtcid = localtcid;
			this.sourcereference = sourcereference;
			this.timeofdeal = timeofdeal;
			this.dealerid = dealerid;
			this.puredealtype = puredealtype;
			this.dealtype = dealtype;
			this.bank1dealingcode = bank1dealingcode;
			this.brokerdealingcode = brokerdealingcode;
			this.currency1 = currency1;
			this.currency2 = currency2;
			this.dealvolumecurrency1 = dealvolumecurrency1;
			this.exchangerateperiod1 = exchangerateperiod1;
			this.exchangerateperiod2 = exchangerateperiod2;
			this.methodofdeal = methodofdeal;
			this.period1 = period1;
			this.period2 = period2;
			this.confirmationtime = confirmationtime;
			this.confirmedbyid = confirmedbyid;
			this.basecurrency = basecurrency;
			this.bank1name = bank1name;
			this.depositrate = depositrate;
			this.swaprate = swaprate;
			this.sourceofdata = sourceofdata;
			this.ratedirection = ratedirection;
			this.valuedateperiod1currency1 = valuedateperiod1currency1;
			this.valuedateperiod1currency2 = valuedateperiod1currency2;
			this.valuedateperiod2currency1 = valuedateperiod2currency1;
			this.valuedateperiod2currency2 = valuedateperiod2currency2;
			this.dealername = dealername;
			this.reviewreferencenumber = reviewreferencenumber;
			this.brokername = brokername;
			this.frafixingdate = frafixingdate;
			this.frasettlementdate = frasettlementdate;
			this.framaturitydate = framaturitydate;
			this.immindicator = immindicator;
			this.outrightpointspremiumrate = outrightpointspremiumrate;
			this.spotbasisrate = spotbasisrate;
			this.conversationtext = conversationtext;
			this.paymentinstructionp1c1 = paymentinstructionp1c1;
			this.paymentinstructionp1c2 = paymentinstructionp1c2;
			this.paymentinstructionp2c1 = paymentinstructionp2c1;
			this.paymentinstructionp2c2 = paymentinstructionp2c2;
			this.secondarysourceref = secondarysourceref;
			this.ratec1usd = ratec1usd;
			this.ratec2usd = ratec2usd;
			this.ratebasecusd = ratebasecusd;
			this.calvolumep1c2 = calvolumep1c2;
			this.calvolumep2c2 = calvolumep2c2;
			this.calvolumep2c1 = calvolumep2c1;
			this.confirmedbyname = confirmedbyname;
			this.commenttext = commenttext;
			this.userdefinedtitle1 = userdefinedtitle1;
			this.userdefineddata1 = userdefineddata1;
			this.userdefinedtitle2 = userdefinedtitle2;
			this.userdefineddata2 = userdefineddata2;
			this.userdefinedtitle3 = userdefinedtitle3;
			this.userdefineddata3 = userdefineddata3;
			this.idifcontra = idifcontra;
			this.idprevious = idprevious;
			this.interestvolume = interestvolume;
			this.elapseddays = elapseddays;
			this.yearlength = yearlength;
			this.priceconvention = priceconvention;
			this.swiftbicc1p1 = swiftbicc1p1;
			this.swiftbicc1p2 = swiftbicc1p2;
			this.swiftbicc2p1 = swiftbicc2p1;
			this.swiftbicc2p2 = swiftbicc2p2;
			this.creditreduction = creditreduction;
			this.creditremaining = creditremaining;
			this.basecurrency2 = basecurrency2;
			this.basecurrency3 = basecurrency3;
			this.ratebasec2usd = ratebasec2usd;
			this.ratebasec3usd = ratebasec3usd;
			this.scope = scope;
			this.customdealingfield1 = customdealingfield1;
			this.customdealingfield2 = customdealingfield2;
			this.customdealingfield3 = customdealingfield3;
			this.midofficecomment = midofficecomment;
			this.autogeneratedticket = autogeneratedticket;
			this.transactionid = transactionid;
			this.startdate = startdate;
			this.enddate = enddate;
			this.deliverydate = deliverydate;
			this.deliverydate2 = deliverydate2;
			this.expirydate = expirydate;
			this.expirydate2 = expirydate2;
			this.paymentdate = paymentdate;
			this.premiumdate = premiumdate;
			this.interestdaybasis = interestdaybasis;
			this.interestdaybasis2 = interestdaybasis2;
			this.index1 = index1;
			this.index2 = index2;
			this.resetfrequency = resetfrequency;
			this.resetbusinessdayconvention = resetbusinessdayconvention;
			this.paymentbusinessdayconvention = paymentbusinessdayconvention;
			this.resetcalendar = resetcalendar;
			this.paymentfrequency = paymentfrequency;
			this.secondaryfrequency = secondaryfrequency;
			this.stubindicator = stubindicator;
			this.stubrate = stubrate;
			this.indexspread = indexspread;
			this.optiontype = optiontype;
			this.optiontype2 = optiontype2;
			this.cutoff = cutoff;
			this.cutoff2 = cutoff2;
			this.expirystyle = expirystyle;
			this.direction2 = direction2;
			this.tradingstrategy = tradingstrategy;
			this.settlement = settlement;
			this.premiumamount = premiumamount;
			this.premiumamount2 = premiumamount2;
			this.volatility = volatility;
			this.volatility2 = volatility2;
			this.premiumquote = premiumquote;
			this.premiumquote2 = premiumquote2;
			this.premiumcurrency = premiumcurrency;
			this.totalnetpremiumamount = totalnetpremiumamount;
			this.premiumquoteconvention = premiumquoteconvention;
			this.hedgedirection = hedgedirection;
			this.hedgedirection2 = hedgedirection2;
			this.hedgevaluedate = hedgevaluedate;
			this.hedgevaluedate2 = hedgevaluedate2;
			this.hedgeamount = hedgeamount;
			this.hedgeamount2 = hedgeamount2;
			this.hedgecontraamount = hedgecontraamount;
			this.hedgecontraamount2 = hedgecontraamount2;
			this.hedgerate = hedgerate;
			this.hedgerate2 = hedgerate2;
			this.depositratereference = depositratereference;
			this.depositratereference2 = depositratereference2;
			this.swappointsreference = swappointsreference;
			this.swappointsreference2 = swappointsreference2;
			this.fixedrate = fixedrate;
			this.bank2name = bank2name;
			this.customdealingfield4 = customdealingfield4;
			this.customdealingfield5 = customdealingfield5;
			this.customdealingfield6 = customdealingfield6;
			this.clearinghouse = clearinghouse;
			this.ourclearingmember = ourclearingmember;
			this.theirclearingmember = theirclearingmember;
			this.onbehalfofname = onbehalfofname;
			this.onbehalfofcode = onbehalfofcode;
			this.premiumdate2 = premiumdate2;
			this.clearingaccount = clearingaccount;
			this.bestbid = bestbid;
			this.bestask = bestask;
			this.ourlei = ourlei;
			this.theirlei = theirlei;
			this.brokerageamount = brokerageamount;
			this.brokeragecurrency = brokeragecurrency;
			this.reportingparty = reportingparty;
			this.namespace = namespace;
			this.linkid = linkid;
			this.transactionid2 = transactionid2;
			this.transactionid3 = transactionid3;
			this.transactionid4 = transactionid4;
			this.transactionidhedge1 = transactionidhedge1;
			this.transactionidhedge2 = transactionidhedge2;
			this.traderepository = traderepository;
			this.midprice = midprice;
			this.ourbiccode = ourbiccode;
			this.theirbiccode = theirbiccode;
			this.executionfacility = executionfacility;
			this.midmarketspotrate = midmarketspotrate;
			this.midmarketnearrate = midmarketnearrate;
			this.midmarketfarrate = midmarketfarrate;
			this.midmarketswaprate = midmarketswaprate;
			this.blocktrade = blocktrade;
			this.clearingeligible = clearingeligible;
			this.ourclearexemp = ourclearexemp;
			this.theirclearexemp = theirclearexemp;
			this.weareusperson = weareusperson;
			this.theyareusperson = theyareusperson;
			this.ourreportjurisd = ourreportjurisd;
			this.theirreportjurisd = theirreportjurisd;
			this.transactionidhedge3 = transactionidhedge3;
			this.transactionidhedge4 = transactionidhedge4;
			this.cpuserid = cpuserid;
			this.cpusername = cpusername;
			this.theirclearingaccount = theirclearingaccount;
			this.uniqueproductid = uniqueproductid;
		}

		@Id
		@Column(name = "TICKETS_ID", unique = true, nullable = false, precision = 22, scale = 0)
		public BigDecimal getTicketsId() {
			return this.ticketsId;
		}

		public void setTicketsId(BigDecimal ticketsId) {
			this.ticketsId = ticketsId;
		}

		@Column(name = "DEALID", length = 15)
		public String getDealid() {
			return this.dealid;
		}

		public void setDealid(String dealid) {
			this.dealid = dealid;
		}

		@Column(name = "PROCESSED", nullable = false, precision = 3, scale = 0)
		public short getProcessed() {
			return this.processed;
		}

		public void setProcessed(short processed) {
			this.processed = processed;
		}

		@Column(name = "PROCESSEDBY", length = 200)
		public String getProcessedby() {
			return this.processedby;
		}

		public void setProcessedby(String processedby) {
			this.processedby = processedby;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "PROCESSEDAT", length = 7)
		public Date getProcessedat() {
			return this.processedat;
		}

		public void setProcessedat(Date processedat) {
			this.processedat = processedat;
		}

		@Column(name = "PROCESSED2", precision = 3, scale = 0)
		public Short getProcessed2() {
			return this.processed2;
		}

		public void setProcessed2(Short processed2) {
			this.processed2 = processed2;
		}

		@Column(name = "PROCESSED2BY", length = 200)
		public String getProcessed2by() {
			return this.processed2by;
		}

		public void setProcessed2by(String processed2by) {
			this.processed2by = processed2by;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "PROCESSED2AT", length = 7)
		public Date getProcessed2at() {
			return this.processed2at;
		}

		public void setProcessed2at(Date processed2at) {
			this.processed2at = processed2at;
		}

		@Column(name = "LASTMODIFIEDBY", length = 200)
		public String getLastmodifiedby() {
			return this.lastmodifiedby;
		}

		public void setLastmodifiedby(String lastmodifiedby) {
			this.lastmodifiedby = lastmodifiedby;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "LASTMODIFIEDAT", length = 7)
		public Date getLastmodifiedat() {
			return this.lastmodifiedat;
		}

		public void setLastmodifiedat(Date lastmodifiedat) {
			this.lastmodifiedat = lastmodifiedat;
		}

		@Column(name = "LOCALTCID", length = 4)
		public String getLocaltcid() {
			return this.localtcid;
		}

		public void setLocaltcid(String localtcid) {
			this.localtcid = localtcid;
		}

		@Column(name = "SOURCEREFERENCE", nullable = false, length = 11)
		public String getSourcereference() {
			return this.sourcereference;
		}

		public void setSourcereference(String sourcereference) {
			this.sourcereference = sourcereference;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "TIMEOFDEAL", nullable = false, length = 7)
		public Date getTimeofdeal() {
			return this.timeofdeal;
		}

		public void setTimeofdeal(Date timeofdeal) {
			this.timeofdeal = timeofdeal;
		}

		@Column(name = "DEALERID", length = 6)
		public String getDealerid() {
			return this.dealerid;
		}

		public void setDealerid(String dealerid) {
			this.dealerid = dealerid;
		}

		@Column(name = "PUREDEALTYPE", precision = 10, scale = 0)
		public Long getPuredealtype() {
			return this.puredealtype;
		}

		public void setPuredealtype(Long puredealtype) {
			this.puredealtype = puredealtype;
		}

		@Column(name = "DEALTYPE", precision = 3, scale = 0)
		public Short getDealtype() {
			return this.dealtype;
		}

		public void setDealtype(Short dealtype) {
			this.dealtype = dealtype;
		}

		@Column(name = "BANK1DEALINGCODE", length = 4)
		public String getBank1dealingcode() {
			return this.bank1dealingcode;
		}

		public void setBank1dealingcode(String bank1dealingcode) {
			this.bank1dealingcode = bank1dealingcode;
		}

		@Column(name = "BROKERDEALINGCODE", length = 4)
		public String getBrokerdealingcode() {
			return this.brokerdealingcode;
		}

		public void setBrokerdealingcode(String brokerdealingcode) {
			this.brokerdealingcode = brokerdealingcode;
		}

		@Column(name = "CURRENCY1", length = 3)
		public String getCurrency1() {
			return this.currency1;
		}

		public void setCurrency1(String currency1) {
			this.currency1 = currency1;
		}

		@Column(name = "CURRENCY2", length = 3)
		public String getCurrency2() {
			return this.currency2;
		}

		public void setCurrency2(String currency2) {
			this.currency2 = currency2;
		}

		@Column(name = "DEALVOLUMECURRENCY1", precision = 22, scale = 0)
		public BigDecimal getDealvolumecurrency1() {
			return this.dealvolumecurrency1;
		}

		public void setDealvolumecurrency1(BigDecimal dealvolumecurrency1) {
			this.dealvolumecurrency1 = dealvolumecurrency1;
		}

		@Column(name = "EXCHANGERATEPERIOD1", precision = 22, scale = 0)
		public BigDecimal getExchangerateperiod1() {
			return this.exchangerateperiod1;
		}

		public void setExchangerateperiod1(BigDecimal exchangerateperiod1) {
			this.exchangerateperiod1 = exchangerateperiod1;
		}

		@Column(name = "EXCHANGERATEPERIOD2", precision = 22, scale = 0)
		public BigDecimal getExchangerateperiod2() {
			return this.exchangerateperiod2;
		}

		public void setExchangerateperiod2(BigDecimal exchangerateperiod2) {
			this.exchangerateperiod2 = exchangerateperiod2;
		}

		@Column(name = "METHODOFDEAL", precision = 3, scale = 0)
		public Short getMethodofdeal() {
			return this.methodofdeal;
		}

		public void setMethodofdeal(Short methodofdeal) {
			this.methodofdeal = methodofdeal;
		}

		@Column(name = "PERIOD1", precision = 10, scale = 0)
		public Long getPeriod1() {
			return this.period1;
		}

		public void setPeriod1(Long period1) {
			this.period1 = period1;
		}

		@Column(name = "PERIOD2", precision = 10, scale = 0)
		public Long getPeriod2() {
			return this.period2;
		}

		public void setPeriod2(Long period2) {
			this.period2 = period2;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "CONFIRMATIONTIME", length = 7)
		public Date getConfirmationtime() {
			return this.confirmationtime;
		}

		public void setConfirmationtime(Date confirmationtime) {
			this.confirmationtime = confirmationtime;
		}

		@Column(name = "CONFIRMEDBYID", length = 6)
		public String getConfirmedbyid() {
			return this.confirmedbyid;
		}

		public void setConfirmedbyid(String confirmedbyid) {
			this.confirmedbyid = confirmedbyid;
		}

		@Column(name = "BASECURRENCY", length = 3)
		public String getBasecurrency() {
			return this.basecurrency;
		}

		public void setBasecurrency(String basecurrency) {
			this.basecurrency = basecurrency;
		}

		@Column(name = "BANK1NAME", length = 56)
		public String getBank1name() {
			return this.bank1name;
		}

		public void setBank1name(String bank1name) {
			this.bank1name = bank1name;
		}

		@Column(name = "DEPOSITRATE", precision = 22, scale = 0)
		public BigDecimal getDepositrate() {
			return this.depositrate;
		}

		public void setDepositrate(BigDecimal depositrate) {
			this.depositrate = depositrate;
		}

		@Column(name = "SWAPRATE", precision = 22, scale = 0)
		public BigDecimal getSwaprate() {
			return this.swaprate;
		}

		public void setSwaprate(BigDecimal swaprate) {
			this.swaprate = swaprate;
		}

		@Column(name = "SOURCEOFDATA", precision = 3, scale = 0)
		public Short getSourceofdata() {
			return this.sourceofdata;
		}

		public void setSourceofdata(Short sourceofdata) {
			this.sourceofdata = sourceofdata;
		}

		@Column(name = "RATEDIRECTION", precision = 3, scale = 0)
		public Short getRatedirection() {
			return this.ratedirection;
		}

		public void setRatedirection(Short ratedirection) {
			this.ratedirection = ratedirection;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "VALUEDATEPERIOD1CURRENCY1", length = 7)
		public Date getValuedateperiod1currency1() {
			return this.valuedateperiod1currency1;
		}

		public void setValuedateperiod1currency1(Date valuedateperiod1currency1) {
			this.valuedateperiod1currency1 = valuedateperiod1currency1;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "VALUEDATEPERIOD1CURRENCY2", length = 7)
		public Date getValuedateperiod1currency2() {
			return this.valuedateperiod1currency2;
		}

		public void setValuedateperiod1currency2(Date valuedateperiod1currency2) {
			this.valuedateperiod1currency2 = valuedateperiod1currency2;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "VALUEDATEPERIOD2CURRENCY1", length = 7)
		public Date getValuedateperiod2currency1() {
			return this.valuedateperiod2currency1;
		}

		public void setValuedateperiod2currency1(Date valuedateperiod2currency1) {
			this.valuedateperiod2currency1 = valuedateperiod2currency1;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "VALUEDATEPERIOD2CURRENCY2", length = 7)
		public Date getValuedateperiod2currency2() {
			return this.valuedateperiod2currency2;
		}

		public void setValuedateperiod2currency2(Date valuedateperiod2currency2) {
			this.valuedateperiod2currency2 = valuedateperiod2currency2;
		}

		@Column(name = "DEALERNAME", length = 20)
		public String getDealername() {
			return this.dealername;
		}

		public void setDealername(String dealername) {
			this.dealername = dealername;
		}

		@Column(name = "REVIEWREFERENCENUMBER", length = 10)
		public String getReviewreferencenumber() {
			return this.reviewreferencenumber;
		}

		public void setReviewreferencenumber(String reviewreferencenumber) {
			this.reviewreferencenumber = reviewreferencenumber;
		}

		@Column(name = "BROKERNAME", length = 56)
		public String getBrokername() {
			return this.brokername;
		}

		public void setBrokername(String brokername) {
			this.brokername = brokername;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "FRAFIXINGDATE", length = 7)
		public Date getFrafixingdate() {
			return this.frafixingdate;
		}

		public void setFrafixingdate(Date frafixingdate) {
			this.frafixingdate = frafixingdate;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "FRASETTLEMENTDATE", length = 7)
		public Date getFrasettlementdate() {
			return this.frasettlementdate;
		}

		public void setFrasettlementdate(Date frasettlementdate) {
			this.frasettlementdate = frasettlementdate;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "FRAMATURITYDATE", length = 7)
		public Date getFramaturitydate() {
			return this.framaturitydate;
		}

		public void setFramaturitydate(Date framaturitydate) {
			this.framaturitydate = framaturitydate;
		}

		@Column(name = "IMMINDICATOR", precision = 3, scale = 0)
		public Short getImmindicator() {
			return this.immindicator;
		}

		public void setImmindicator(Short immindicator) {
			this.immindicator = immindicator;
		}

		@Column(name = "OUTRIGHTPOINTSPREMIUMRATE", precision = 22, scale = 0)
		public BigDecimal getOutrightpointspremiumrate() {
			return this.outrightpointspremiumrate;
		}

		public void setOutrightpointspremiumrate(
				BigDecimal outrightpointspremiumrate) {
			this.outrightpointspremiumrate = outrightpointspremiumrate;
		}

		@Column(name = "SPOTBASISRATE", precision = 22, scale = 0)
		public BigDecimal getSpotbasisrate() {
			return this.spotbasisrate;
		}

		public void setSpotbasisrate(BigDecimal spotbasisrate) {
			this.spotbasisrate = spotbasisrate;
		}

		@Column(name = "CONVERSATIONTEXT")
		public Clob getConversationtext() {
			return this.conversationtext;
		}

		public void setConversationtext(Clob conversationtext) {
			this.conversationtext = conversationtext;
		}

		@Column(name = "PAYMENTINSTRUCTIONP1C1", length = 80)
		public String getPaymentinstructionp1c1() {
			return this.paymentinstructionp1c1;
		}

		public void setPaymentinstructionp1c1(String paymentinstructionp1c1) {
			this.paymentinstructionp1c1 = paymentinstructionp1c1;
		}

		@Column(name = "PAYMENTINSTRUCTIONP1C2", length = 80)
		public String getPaymentinstructionp1c2() {
			return this.paymentinstructionp1c2;
		}

		public void setPaymentinstructionp1c2(String paymentinstructionp1c2) {
			this.paymentinstructionp1c2 = paymentinstructionp1c2;
		}

		@Column(name = "PAYMENTINSTRUCTIONP2C1", length = 80)
		public String getPaymentinstructionp2c1() {
			return this.paymentinstructionp2c1;
		}

		public void setPaymentinstructionp2c1(String paymentinstructionp2c1) {
			this.paymentinstructionp2c1 = paymentinstructionp2c1;
		}

		@Column(name = "PAYMENTINSTRUCTIONP2C2", length = 80)
		public String getPaymentinstructionp2c2() {
			return this.paymentinstructionp2c2;
		}

		public void setPaymentinstructionp2c2(String paymentinstructionp2c2) {
			this.paymentinstructionp2c2 = paymentinstructionp2c2;
		}

		@Column(name = "SECONDARYSOURCEREF", length = 10)
		public String getSecondarysourceref() {
			return this.secondarysourceref;
		}

		public void setSecondarysourceref(String secondarysourceref) {
			this.secondarysourceref = secondarysourceref;
		}

		@Column(name = "RATEC1USD", precision = 22, scale = 0)
		public BigDecimal getRatec1usd() {
			return this.ratec1usd;
		}

		public void setRatec1usd(BigDecimal ratec1usd) {
			this.ratec1usd = ratec1usd;
		}

		@Column(name = "RATEC2USD", precision = 22, scale = 0)
		public BigDecimal getRatec2usd() {
			return this.ratec2usd;
		}

		public void setRatec2usd(BigDecimal ratec2usd) {
			this.ratec2usd = ratec2usd;
		}

		@Column(name = "RATEBASECUSD", precision = 22, scale = 0)
		public BigDecimal getRatebasecusd() {
			return this.ratebasecusd;
		}

		public void setRatebasecusd(BigDecimal ratebasecusd) {
			this.ratebasecusd = ratebasecusd;
		}

		@Column(name = "CALVOLUMEP1C2", precision = 22, scale = 0)
		public BigDecimal getCalvolumep1c2() {
			return this.calvolumep1c2;
		}

		public void setCalvolumep1c2(BigDecimal calvolumep1c2) {
			this.calvolumep1c2 = calvolumep1c2;
		}

		@Column(name = "CALVOLUMEP2C2", precision = 22, scale = 0)
		public BigDecimal getCalvolumep2c2() {
			return this.calvolumep2c2;
		}

		public void setCalvolumep2c2(BigDecimal calvolumep2c2) {
			this.calvolumep2c2 = calvolumep2c2;
		}

		@Column(name = "CALVOLUMEP2C1", precision = 22, scale = 0)
		public BigDecimal getCalvolumep2c1() {
			return this.calvolumep2c1;
		}

		public void setCalvolumep2c1(BigDecimal calvolumep2c1) {
			this.calvolumep2c1 = calvolumep2c1;
		}

		@Column(name = "CONFIRMEDBYNAME", length = 30)
		public String getConfirmedbyname() {
			return this.confirmedbyname;
		}

		public void setConfirmedbyname(String confirmedbyname) {
			this.confirmedbyname = confirmedbyname;
		}

		@Column(name = "COMMENTTEXT", length = 124)
		public String getCommenttext() {
			return this.commenttext;
		}

		public void setCommenttext(String commenttext) {
			this.commenttext = commenttext;
		}

		@Column(name = "USERDEFINEDTITLE1", length = 20)
		public String getUserdefinedtitle1() {
			return this.userdefinedtitle1;
		}

		public void setUserdefinedtitle1(String userdefinedtitle1) {
			this.userdefinedtitle1 = userdefinedtitle1;
		}

		@Column(name = "USERDEFINEDDATA1", length = 40)
		public String getUserdefineddata1() {
			return this.userdefineddata1;
		}

		public void setUserdefineddata1(String userdefineddata1) {
			this.userdefineddata1 = userdefineddata1;
		}

		@Column(name = "USERDEFINEDTITLE2", length = 20)
		public String getUserdefinedtitle2() {
			return this.userdefinedtitle2;
		}

		public void setUserdefinedtitle2(String userdefinedtitle2) {
			this.userdefinedtitle2 = userdefinedtitle2;
		}

		@Column(name = "USERDEFINEDDATA2", length = 40)
		public String getUserdefineddata2() {
			return this.userdefineddata2;
		}

		public void setUserdefineddata2(String userdefineddata2) {
			this.userdefineddata2 = userdefineddata2;
		}

		@Column(name = "USERDEFINEDTITLE3", length = 20)
		public String getUserdefinedtitle3() {
			return this.userdefinedtitle3;
		}

		public void setUserdefinedtitle3(String userdefinedtitle3) {
			this.userdefinedtitle3 = userdefinedtitle3;
		}

		@Column(name = "USERDEFINEDDATA3", length = 40)
		public String getUserdefineddata3() {
			return this.userdefineddata3;
		}

		public void setUserdefineddata3(String userdefineddata3) {
			this.userdefineddata3 = userdefineddata3;
		}

		@Column(name = "IDIFCONTRA", length = 11)
		public String getIdifcontra() {
			return this.idifcontra;
		}

		public void setIdifcontra(String idifcontra) {
			this.idifcontra = idifcontra;
		}

		@Column(name = "IDPREVIOUS", length = 11)
		public String getIdprevious() {
			return this.idprevious;
		}

		public void setIdprevious(String idprevious) {
			this.idprevious = idprevious;
		}

		@Column(name = "INTERESTVOLUME", precision = 22, scale = 0)
		public BigDecimal getInterestvolume() {
			return this.interestvolume;
		}

		public void setInterestvolume(BigDecimal interestvolume) {
			this.interestvolume = interestvolume;
		}

		@Column(name = "ELAPSEDDAYS", precision = 10, scale = 0)
		public Long getElapseddays() {
			return this.elapseddays;
		}

		public void setElapseddays(Long elapseddays) {
			this.elapseddays = elapseddays;
		}

		@Column(name = "YEARLENGTH", precision = 10, scale = 0)
		public Long getYearlength() {
			return this.yearlength;
		}

		public void setYearlength(Long yearlength) {
			this.yearlength = yearlength;
		}

		@Column(name = "PRICECONVENTION", precision = 10, scale = 0)
		public Long getPriceconvention() {
			return this.priceconvention;
		}

		public void setPriceconvention(Long priceconvention) {
			this.priceconvention = priceconvention;
		}

		@Column(name = "SWIFTBICC1P1", length = 11)
		public String getSwiftbicc1p1() {
			return this.swiftbicc1p1;
		}

		public void setSwiftbicc1p1(String swiftbicc1p1) {
			this.swiftbicc1p1 = swiftbicc1p1;
		}

		@Column(name = "SWIFTBICC1P2", length = 11)
		public String getSwiftbicc1p2() {
			return this.swiftbicc1p2;
		}

		public void setSwiftbicc1p2(String swiftbicc1p2) {
			this.swiftbicc1p2 = swiftbicc1p2;
		}

		@Column(name = "SWIFTBICC2P1", length = 11)
		public String getSwiftbicc2p1() {
			return this.swiftbicc2p1;
		}

		public void setSwiftbicc2p1(String swiftbicc2p1) {
			this.swiftbicc2p1 = swiftbicc2p1;
		}

		@Column(name = "SWIFTBICC2P2", length = 11)
		public String getSwiftbicc2p2() {
			return this.swiftbicc2p2;
		}

		public void setSwiftbicc2p2(String swiftbicc2p2) {
			this.swiftbicc2p2 = swiftbicc2p2;
		}

		@Column(name = "CREDITREDUCTION", precision = 22, scale = 0)
		public BigDecimal getCreditreduction() {
			return this.creditreduction;
		}

		public void setCreditreduction(BigDecimal creditreduction) {
			this.creditreduction = creditreduction;
		}

		@Column(name = "CREDITREMAINING", precision = 22, scale = 0)
		public BigDecimal getCreditremaining() {
			return this.creditremaining;
		}

		public void setCreditremaining(BigDecimal creditremaining) {
			this.creditremaining = creditremaining;
		}

		@Column(name = "BASECURRENCY2", length = 3)
		public String getBasecurrency2() {
			return this.basecurrency2;
		}

		public void setBasecurrency2(String basecurrency2) {
			this.basecurrency2 = basecurrency2;
		}

		@Column(name = "BASECURRENCY3", length = 3)
		public String getBasecurrency3() {
			return this.basecurrency3;
		}

		public void setBasecurrency3(String basecurrency3) {
			this.basecurrency3 = basecurrency3;
		}

		@Column(name = "RATEBASEC2USD", precision = 22, scale = 0)
		public BigDecimal getRatebasec2usd() {
			return this.ratebasec2usd;
		}

		public void setRatebasec2usd(BigDecimal ratebasec2usd) {
			this.ratebasec2usd = ratebasec2usd;
		}

		@Column(name = "RATEBASEC3USD", precision = 22, scale = 0)
		public BigDecimal getRatebasec3usd() {
			return this.ratebasec3usd;
		}

		public void setRatebasec3usd(BigDecimal ratebasec3usd) {
			this.ratebasec3usd = ratebasec3usd;
		}

		@Column(name = "SCOPE", precision = 10, scale = 0)
		public Long getScope() {
			return this.scope;
		}

		public void setScope(Long scope) {
			this.scope = scope;
		}

		@Column(name = "CUSTOMDEALINGFIELD1", length = 200)
		public String getCustomdealingfield1() {
			return this.customdealingfield1;
		}

		public void setCustomdealingfield1(String customdealingfield1) {
			this.customdealingfield1 = customdealingfield1;
		}

		@Column(name = "CUSTOMDEALINGFIELD2", length = 200)
		public String getCustomdealingfield2() {
			return this.customdealingfield2;
		}

		public void setCustomdealingfield2(String customdealingfield2) {
			this.customdealingfield2 = customdealingfield2;
		}

		@Column(name = "CUSTOMDEALINGFIELD3", length = 200)
		public String getCustomdealingfield3() {
			return this.customdealingfield3;
		}

		public void setCustomdealingfield3(String customdealingfield3) {
			this.customdealingfield3 = customdealingfield3;
		}

		@Column(name = "MIDOFFICECOMMENT", length = 200)
		public String getMidofficecomment() {
			return this.midofficecomment;
		}

		public void setMidofficecomment(String midofficecomment) {
			this.midofficecomment = midofficecomment;
		}

		@Column(name = "AUTOGENERATEDTICKET", precision = 3, scale = 0)
		public Short getAutogeneratedticket() {
			return this.autogeneratedticket;
		}

		public void setAutogeneratedticket(Short autogeneratedticket) {
			this.autogeneratedticket = autogeneratedticket;
		}

		@Column(name = "TRANSACTIONID", length = 52)
		public String getTransactionid() {
			return this.transactionid;
		}

		public void setTransactionid(String transactionid) {
			this.transactionid = transactionid;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "STARTDATE", length = 7)
		public Date getStartdate() {
			return this.startdate;
		}

		public void setStartdate(Date startdate) {
			this.startdate = startdate;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "ENDDATE", length = 7)
		public Date getEnddate() {
			return this.enddate;
		}

		public void setEnddate(Date enddate) {
			this.enddate = enddate;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "DELIVERYDATE", length = 7)
		public Date getDeliverydate() {
			return this.deliverydate;
		}

		public void setDeliverydate(Date deliverydate) {
			this.deliverydate = deliverydate;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "DELIVERYDATE2", length = 7)
		public Date getDeliverydate2() {
			return this.deliverydate2;
		}

		public void setDeliverydate2(Date deliverydate2) {
			this.deliverydate2 = deliverydate2;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "EXPIRYDATE", length = 7)
		public Date getExpirydate() {
			return this.expirydate;
		}

		public void setExpirydate(Date expirydate) {
			this.expirydate = expirydate;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "EXPIRYDATE2", length = 7)
		public Date getExpirydate2() {
			return this.expirydate2;
		}

		public void setExpirydate2(Date expirydate2) {
			this.expirydate2 = expirydate2;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "PAYMENTDATE", length = 7)
		public Date getPaymentdate() {
			return this.paymentdate;
		}

		public void setPaymentdate(Date paymentdate) {
			this.paymentdate = paymentdate;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "PREMIUMDATE", length = 7)
		public Date getPremiumdate() {
			return this.premiumdate;
		}

		public void setPremiumdate(Date premiumdate) {
			this.premiumdate = premiumdate;
		}

		@Column(name = "INTERESTDAYBASIS", length = 10)
		public String getInterestdaybasis() {
			return this.interestdaybasis;
		}

		public void setInterestdaybasis(String interestdaybasis) {
			this.interestdaybasis = interestdaybasis;
		}

		@Column(name = "INTERESTDAYBASIS2", length = 10)
		public String getInterestdaybasis2() {
			return this.interestdaybasis2;
		}

		public void setInterestdaybasis2(String interestdaybasis2) {
			this.interestdaybasis2 = interestdaybasis2;
		}

		@Column(name = "INDEX1", length = 20)
		public String getIndex1() {
			return this.index1;
		}

		public void setIndex1(String index1) {
			this.index1 = index1;
		}

		@Column(name = "INDEX2", length = 20)
		public String getIndex2() {
			return this.index2;
		}

		public void setIndex2(String index2) {
			this.index2 = index2;
		}

		@Column(name = "RESETFREQUENCY", precision = 3, scale = 0)
		public Short getResetfrequency() {
			return this.resetfrequency;
		}

		public void setResetfrequency(Short resetfrequency) {
			this.resetfrequency = resetfrequency;
		}

		@Column(name = "RESETBUSINESSDAYCONVENTION", precision = 2, scale = 0)
		public Byte getResetbusinessdayconvention() {
			return this.resetbusinessdayconvention;
		}

		public void setResetbusinessdayconvention(Byte resetbusinessdayconvention) {
			this.resetbusinessdayconvention = resetbusinessdayconvention;
		}

		@Column(name = "PAYMENTBUSINESSDAYCONVENTION", precision = 2, scale = 0)
		public Byte getPaymentbusinessdayconvention() {
			return this.paymentbusinessdayconvention;
		}

		public void setPaymentbusinessdayconvention(
				Byte paymentbusinessdayconvention) {
			this.paymentbusinessdayconvention = paymentbusinessdayconvention;
		}

		@Column(name = "RESETCALENDAR", length = 20)
		public String getResetcalendar() {
			return this.resetcalendar;
		}

		public void setResetcalendar(String resetcalendar) {
			this.resetcalendar = resetcalendar;
		}

		@Column(name = "PAYMENTFREQUENCY", precision = 3, scale = 0)
		public Short getPaymentfrequency() {
			return this.paymentfrequency;
		}

		public void setPaymentfrequency(Short paymentfrequency) {
			this.paymentfrequency = paymentfrequency;
		}

		@Column(name = "SECONDARYFREQUENCY", precision = 3, scale = 0)
		public Short getSecondaryfrequency() {
			return this.secondaryfrequency;
		}

		public void setSecondaryfrequency(Short secondaryfrequency) {
			this.secondaryfrequency = secondaryfrequency;
		}

		@Column(name = "STUBINDICATOR", length = 20)
		public String getStubindicator() {
			return this.stubindicator;
		}

		public void setStubindicator(String stubindicator) {
			this.stubindicator = stubindicator;
		}

		@Column(name = "STUBRATE", precision = 22, scale = 15)
		public BigDecimal getStubrate() {
			return this.stubrate;
		}

		public void setStubrate(BigDecimal stubrate) {
			this.stubrate = stubrate;
		}

		@Column(name = "INDEXSPREAD", precision = 22, scale = 15)
		public BigDecimal getIndexspread() {
			return this.indexspread;
		}

		public void setIndexspread(BigDecimal indexspread) {
			this.indexspread = indexspread;
		}

		@Column(name = "OPTIONTYPE", length = 10)
		public String getOptiontype() {
			return this.optiontype;
		}

		public void setOptiontype(String optiontype) {
			this.optiontype = optiontype;
		}

		@Column(name = "OPTIONTYPE2", length = 10)
		public String getOptiontype2() {
			return this.optiontype2;
		}

		public void setOptiontype2(String optiontype2) {
			this.optiontype2 = optiontype2;
		}

		@Column(name = "CUTOFF", length = 20)
		public String getCutoff() {
			return this.cutoff;
		}

		public void setCutoff(String cutoff) {
			this.cutoff = cutoff;
		}

		@Column(name = "CUTOFF2", length = 20)
		public String getCutoff2() {
			return this.cutoff2;
		}

		public void setCutoff2(String cutoff2) {
			this.cutoff2 = cutoff2;
		}

		@Column(name = "EXPIRYSTYLE", precision = 2, scale = 0)
		public Byte getExpirystyle() {
			return this.expirystyle;
		}

		public void setExpirystyle(Byte expirystyle) {
			this.expirystyle = expirystyle;
		}

		@Column(name = "DIRECTION2", precision = 2, scale = 0)
		public Byte getDirection2() {
			return this.direction2;
		}

		public void setDirection2(Byte direction2) {
			this.direction2 = direction2;
		}

		@Column(name = "TRADINGSTRATEGY", precision = 2, scale = 0)
		public Byte getTradingstrategy() {
			return this.tradingstrategy;
		}

		public void setTradingstrategy(Byte tradingstrategy) {
			this.tradingstrategy = tradingstrategy;
		}

		@Column(name = "SETTLEMENT", precision = 2, scale = 0)
		public Byte getSettlement() {
			return this.settlement;
		}

		public void setSettlement(Byte settlement) {
			this.settlement = settlement;
		}

		@Column(name = "PREMIUMAMOUNT", precision = 22, scale = 15)
		public BigDecimal getPremiumamount() {
			return this.premiumamount;
		}

		public void setPremiumamount(BigDecimal premiumamount) {
			this.premiumamount = premiumamount;
		}

		@Column(name = "PREMIUMAMOUNT2", precision = 22, scale = 15)
		public BigDecimal getPremiumamount2() {
			return this.premiumamount2;
		}

		public void setPremiumamount2(BigDecimal premiumamount2) {
			this.premiumamount2 = premiumamount2;
		}

		@Column(name = "VOLATILITY", precision = 22, scale = 15)
		public BigDecimal getVolatility() {
			return this.volatility;
		}

		public void setVolatility(BigDecimal volatility) {
			this.volatility = volatility;
		}

		@Column(name = "VOLATILITY2", precision = 22, scale = 15)
		public BigDecimal getVolatility2() {
			return this.volatility2;
		}

		public void setVolatility2(BigDecimal volatility2) {
			this.volatility2 = volatility2;
		}

		@Column(name = "PREMIUMQUOTE", precision = 22, scale = 15)
		public BigDecimal getPremiumquote() {
			return this.premiumquote;
		}

		public void setPremiumquote(BigDecimal premiumquote) {
			this.premiumquote = premiumquote;
		}

		@Column(name = "PREMIUMQUOTE2", precision = 22, scale = 15)
		public BigDecimal getPremiumquote2() {
			return this.premiumquote2;
		}

		public void setPremiumquote2(BigDecimal premiumquote2) {
			this.premiumquote2 = premiumquote2;
		}

		@Column(name = "PREMIUMCURRENCY", length = 3)
		public String getPremiumcurrency() {
			return this.premiumcurrency;
		}

		public void setPremiumcurrency(String premiumcurrency) {
			this.premiumcurrency = premiumcurrency;
		}

		@Column(name = "TOTALNETPREMIUMAMOUNT", precision = 22, scale = 15)
		public BigDecimal getTotalnetpremiumamount() {
			return this.totalnetpremiumamount;
		}

		public void setTotalnetpremiumamount(BigDecimal totalnetpremiumamount) {
			this.totalnetpremiumamount = totalnetpremiumamount;
		}

		@Column(name = "PREMIUMQUOTECONVENTION", precision = 2, scale = 0)
		public Byte getPremiumquoteconvention() {
			return this.premiumquoteconvention;
		}

		public void setPremiumquoteconvention(Byte premiumquoteconvention) {
			this.premiumquoteconvention = premiumquoteconvention;
		}

		@Column(name = "HEDGEDIRECTION", precision = 2, scale = 0)
		public Byte getHedgedirection() {
			return this.hedgedirection;
		}

		public void setHedgedirection(Byte hedgedirection) {
			this.hedgedirection = hedgedirection;
		}

		@Column(name = "HEDGEDIRECTION2", precision = 2, scale = 0)
		public Byte getHedgedirection2() {
			return this.hedgedirection2;
		}

		public void setHedgedirection2(Byte hedgedirection2) {
			this.hedgedirection2 = hedgedirection2;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "HEDGEVALUEDATE", length = 7)
		public Date getHedgevaluedate() {
			return this.hedgevaluedate;
		}

		public void setHedgevaluedate(Date hedgevaluedate) {
			this.hedgevaluedate = hedgevaluedate;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "HEDGEVALUEDATE2", length = 7)
		public Date getHedgevaluedate2() {
			return this.hedgevaluedate2;
		}

		public void setHedgevaluedate2(Date hedgevaluedate2) {
			this.hedgevaluedate2 = hedgevaluedate2;
		}

		@Column(name = "HEDGEAMOUNT", precision = 22, scale = 15)
		public BigDecimal getHedgeamount() {
			return this.hedgeamount;
		}

		public void setHedgeamount(BigDecimal hedgeamount) {
			this.hedgeamount = hedgeamount;
		}

		@Column(name = "HEDGEAMOUNT2", precision = 22, scale = 15)
		public BigDecimal getHedgeamount2() {
			return this.hedgeamount2;
		}

		public void setHedgeamount2(BigDecimal hedgeamount2) {
			this.hedgeamount2 = hedgeamount2;
		}

		@Column(name = "HEDGECONTRAAMOUNT", precision = 22, scale = 15)
		public BigDecimal getHedgecontraamount() {
			return this.hedgecontraamount;
		}

		public void setHedgecontraamount(BigDecimal hedgecontraamount) {
			this.hedgecontraamount = hedgecontraamount;
		}

		@Column(name = "HEDGECONTRAAMOUNT2", precision = 22, scale = 15)
		public BigDecimal getHedgecontraamount2() {
			return this.hedgecontraamount2;
		}

		public void setHedgecontraamount2(BigDecimal hedgecontraamount2) {
			this.hedgecontraamount2 = hedgecontraamount2;
		}

		@Column(name = "HEDGERATE", precision = 22, scale = 15)
		public BigDecimal getHedgerate() {
			return this.hedgerate;
		}

		public void setHedgerate(BigDecimal hedgerate) {
			this.hedgerate = hedgerate;
		}

		@Column(name = "HEDGERATE2", precision = 22, scale = 15)
		public BigDecimal getHedgerate2() {
			return this.hedgerate2;
		}

		public void setHedgerate2(BigDecimal hedgerate2) {
			this.hedgerate2 = hedgerate2;
		}

		@Column(name = "DEPOSITRATEREFERENCE", precision = 22, scale = 15)
		public BigDecimal getDepositratereference() {
			return this.depositratereference;
		}

		public void setDepositratereference(BigDecimal depositratereference) {
			this.depositratereference = depositratereference;
		}

		@Column(name = "DEPOSITRATEREFERENCE2", precision = 22, scale = 15)
		public BigDecimal getDepositratereference2() {
			return this.depositratereference2;
		}

		public void setDepositratereference2(BigDecimal depositratereference2) {
			this.depositratereference2 = depositratereference2;
		}

		@Column(name = "SWAPPOINTSREFERENCE", precision = 22, scale = 15)
		public BigDecimal getSwappointsreference() {
			return this.swappointsreference;
		}

		public void setSwappointsreference(BigDecimal swappointsreference) {
			this.swappointsreference = swappointsreference;
		}

		@Column(name = "SWAPPOINTSREFERENCE2", precision = 22, scale = 15)
		public BigDecimal getSwappointsreference2() {
			return this.swappointsreference2;
		}

		public void setSwappointsreference2(BigDecimal swappointsreference2) {
			this.swappointsreference2 = swappointsreference2;
		}

		@Column(name = "FIXEDRATE", precision = 22, scale = 15)
		public BigDecimal getFixedrate() {
			return this.fixedrate;
		}

		public void setFixedrate(BigDecimal fixedrate) {
			this.fixedrate = fixedrate;
		}

		@Column(name = "BANK2NAME", length = 56)
		public String getBank2name() {
			return this.bank2name;
		}

		public void setBank2name(String bank2name) {
			this.bank2name = bank2name;
		}

		@Column(name = "CUSTOMDEALINGFIELD4", length = 200)
		public String getCustomdealingfield4() {
			return this.customdealingfield4;
		}

		public void setCustomdealingfield4(String customdealingfield4) {
			this.customdealingfield4 = customdealingfield4;
		}

		@Column(name = "CUSTOMDEALINGFIELD5", length = 200)
		public String getCustomdealingfield5() {
			return this.customdealingfield5;
		}

		public void setCustomdealingfield5(String customdealingfield5) {
			this.customdealingfield5 = customdealingfield5;
		}

		@Column(name = "CUSTOMDEALINGFIELD6", length = 200)
		public String getCustomdealingfield6() {
			return this.customdealingfield6;
		}

		public void setCustomdealingfield6(String customdealingfield6) {
			this.customdealingfield6 = customdealingfield6;
		}

		@Column(name = "CLEARINGHOUSE", length = 20)
		public String getClearinghouse() {
			return this.clearinghouse;
		}

		public void setClearinghouse(String clearinghouse) {
			this.clearinghouse = clearinghouse;
		}

		@Column(name = "OURCLEARINGMEMBER", length = 40)
		public String getOurclearingmember() {
			return this.ourclearingmember;
		}

		public void setOurclearingmember(String ourclearingmember) {
			this.ourclearingmember = ourclearingmember;
		}

		@Column(name = "THEIRCLEARINGMEMBER", length = 40)
		public String getTheirclearingmember() {
			return this.theirclearingmember;
		}

		public void setTheirclearingmember(String theirclearingmember) {
			this.theirclearingmember = theirclearingmember;
		}

		@Column(name = "ONBEHALFOFNAME", length = 64)
		public String getOnbehalfofname() {
			return this.onbehalfofname;
		}

		public void setOnbehalfofname(String onbehalfofname) {
			this.onbehalfofname = onbehalfofname;
		}

		@Column(name = "ONBEHALFOFCODE", length = 4)
		public String getOnbehalfofcode() {
			return this.onbehalfofcode;
		}

		public void setOnbehalfofcode(String onbehalfofcode) {
			this.onbehalfofcode = onbehalfofcode;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "PREMIUMDATE2", length = 7)
		public Date getPremiumdate2() {
			return this.premiumdate2;
		}

		public void setPremiumdate2(Date premiumdate2) {
			this.premiumdate2 = premiumdate2;
		}

		@Column(name = "CLEARINGACCOUNT", length = 80)
		public String getClearingaccount() {
			return this.clearingaccount;
		}

		public void setClearingaccount(String clearingaccount) {
			this.clearingaccount = clearingaccount;
		}

		@Column(name = "BESTBID", precision = 22, scale = 17)
		public BigDecimal getBestbid() {
			return this.bestbid;
		}

		public void setBestbid(BigDecimal bestbid) {
			this.bestbid = bestbid;
		}

		@Column(name = "BESTASK", precision = 22, scale = 17)
		public BigDecimal getBestask() {
			return this.bestask;
		}

		public void setBestask(BigDecimal bestask) {
			this.bestask = bestask;
		}

		@Column(name = "OURLEI", length = 20)
		public String getOurlei() {
			return this.ourlei;
		}

		public void setOurlei(String ourlei) {
			this.ourlei = ourlei;
		}

		@Column(name = "THEIRLEI", length = 20)
		public String getTheirlei() {
			return this.theirlei;
		}

		public void setTheirlei(String theirlei) {
			this.theirlei = theirlei;
		}

		@Column(name = "BROKERAGEAMOUNT", precision = 22, scale = 17)
		public BigDecimal getBrokerageamount() {
			return this.brokerageamount;
		}

		public void setBrokerageamount(BigDecimal brokerageamount) {
			this.brokerageamount = brokerageamount;
		}

		@Column(name = "BROKERAGECURRENCY", length = 80)
		public String getBrokeragecurrency() {
			return this.brokeragecurrency;
		}

		public void setBrokeragecurrency(String brokeragecurrency) {
			this.brokeragecurrency = brokeragecurrency;
		}

		@Column(name = "REPORTINGPARTY", length = 80)
		public String getReportingparty() {
			return this.reportingparty;
		}

		public void setReportingparty(String reportingparty) {
			this.reportingparty = reportingparty;
		}

		@Column(name = "NAMESPACE", length = 80)
		public String getNamespace() {
			return this.namespace;
		}

		public void setNamespace(String namespace) {
			this.namespace = namespace;
		}

		@Column(name = "LINKID", length = 80)
		public String getLinkid() {
			return this.linkid;
		}

		public void setLinkid(String linkid) {
			this.linkid = linkid;
		}

		@Column(name = "TRANSACTIONID2", length = 80)
		public String getTransactionid2() {
			return this.transactionid2;
		}

		public void setTransactionid2(String transactionid2) {
			this.transactionid2 = transactionid2;
		}

		@Column(name = "TRANSACTIONID3", length = 80)
		public String getTransactionid3() {
			return this.transactionid3;
		}

		public void setTransactionid3(String transactionid3) {
			this.transactionid3 = transactionid3;
		}

		@Column(name = "TRANSACTIONID4", length = 80)
		public String getTransactionid4() {
			return this.transactionid4;
		}

		public void setTransactionid4(String transactionid4) {
			this.transactionid4 = transactionid4;
		}

		@Column(name = "TRANSACTIONIDHEDGE1", length = 80)
		public String getTransactionidhedge1() {
			return this.transactionidhedge1;
		}

		public void setTransactionidhedge1(String transactionidhedge1) {
			this.transactionidhedge1 = transactionidhedge1;
		}

		@Column(name = "TRANSACTIONIDHEDGE2", length = 80)
		public String getTransactionidhedge2() {
			return this.transactionidhedge2;
		}

		public void setTransactionidhedge2(String transactionidhedge2) {
			this.transactionidhedge2 = transactionidhedge2;
		}

		@Column(name = "TRADEREPOSITORY", length = 80)
		public String getTraderepository() {
			return this.traderepository;
		}

		public void setTraderepository(String traderepository) {
			this.traderepository = traderepository;
		}

		@Column(name = "MIDPRICE", precision = 22, scale = 17)
		public BigDecimal getMidprice() {
			return this.midprice;
		}

		public void setMidprice(BigDecimal midprice) {
			this.midprice = midprice;
		}

		@Column(name = "OURBICCODE", length = 11)
		public String getOurbiccode() {
			return this.ourbiccode;
		}

		public void setOurbiccode(String ourbiccode) {
			this.ourbiccode = ourbiccode;
		}

		@Column(name = "THEIRBICCODE", length = 11)
		public String getTheirbiccode() {
			return this.theirbiccode;
		}

		public void setTheirbiccode(String theirbiccode) {
			this.theirbiccode = theirbiccode;
		}

		@Column(name = "EXECUTIONFACILITY", length = 40)
		public String getExecutionfacility() {
			return this.executionfacility;
		}

		public void setExecutionfacility(String executionfacility) {
			this.executionfacility = executionfacility;
		}

		@Column(name = "MIDMARKETSPOTRATE", precision = 22, scale = 17)
		public BigDecimal getMidmarketspotrate() {
			return this.midmarketspotrate;
		}

		public void setMidmarketspotrate(BigDecimal midmarketspotrate) {
			this.midmarketspotrate = midmarketspotrate;
		}

		@Column(name = "MIDMARKETNEARRATE", precision = 22, scale = 17)
		public BigDecimal getMidmarketnearrate() {
			return this.midmarketnearrate;
		}

		public void setMidmarketnearrate(BigDecimal midmarketnearrate) {
			this.midmarketnearrate = midmarketnearrate;
		}

		@Column(name = "MIDMARKETFARRATE", precision = 22, scale = 17)
		public BigDecimal getMidmarketfarrate() {
			return this.midmarketfarrate;
		}

		public void setMidmarketfarrate(BigDecimal midmarketfarrate) {
			this.midmarketfarrate = midmarketfarrate;
		}

		@Column(name = "MIDMARKETSWAPRATE", precision = 22, scale = 17)
		public BigDecimal getMidmarketswaprate() {
			return this.midmarketswaprate;
		}

		public void setMidmarketswaprate(BigDecimal midmarketswaprate) {
			this.midmarketswaprate = midmarketswaprate;
		}

		@Column(name = "BLOCKTRADE", precision = 3, scale = 0)
		public Short getBlocktrade() {
			return this.blocktrade;
		}

		public void setBlocktrade(Short blocktrade) {
			this.blocktrade = blocktrade;
		}

		@Column(name = "CLEARINGELIGIBLE", precision = 3, scale = 0)
		public Short getClearingeligible() {
			return this.clearingeligible;
		}

		public void setClearingeligible(Short clearingeligible) {
			this.clearingeligible = clearingeligible;
		}

		@Column(name = "OURCLEAREXEMP", precision = 3, scale = 0)
		public Short getOurclearexemp() {
			return this.ourclearexemp;
		}

		public void setOurclearexemp(Short ourclearexemp) {
			this.ourclearexemp = ourclearexemp;
		}

		@Column(name = "THEIRCLEAREXEMP", precision = 3, scale = 0)
		public Short getTheirclearexemp() {
			return this.theirclearexemp;
		}

		public void setTheirclearexemp(Short theirclearexemp) {
			this.theirclearexemp = theirclearexemp;
		}

		@Column(name = "WEAREUSPERSON", precision = 3, scale = 0)
		public Short getWeareusperson() {
			return this.weareusperson;
		}

		public void setWeareusperson(Short weareusperson) {
			this.weareusperson = weareusperson;
		}

		@Column(name = "THEYAREUSPERSON", precision = 3, scale = 0)
		public Short getTheyareusperson() {
			return this.theyareusperson;
		}

		public void setTheyareusperson(Short theyareusperson) {
			this.theyareusperson = theyareusperson;
		}

		@Column(name = "OURREPORTJURISD", length = 40)
		public String getOurreportjurisd() {
			return this.ourreportjurisd;
		}

		public void setOurreportjurisd(String ourreportjurisd) {
			this.ourreportjurisd = ourreportjurisd;
		}

		@Column(name = "THEIRREPORTJURISD", length = 40)
		public String getTheirreportjurisd() {
			return this.theirreportjurisd;
		}

		public void setTheirreportjurisd(String theirreportjurisd) {
			this.theirreportjurisd = theirreportjurisd;
		}

		@Column(name = "TRANSACTIONIDHEDGE3", length = 80)
		public String getTransactionidhedge3() {
			return this.transactionidhedge3;
		}

		public void setTransactionidhedge3(String transactionidhedge3) {
			this.transactionidhedge3 = transactionidhedge3;
		}

		@Column(name = "TRANSACTIONIDHEDGE4", length = 80)
		public String getTransactionidhedge4() {
			return this.transactionidhedge4;
		}

		public void setTransactionidhedge4(String transactionidhedge4) {
			this.transactionidhedge4 = transactionidhedge4;
		}

		@Column(name = "CPUSERID", length = 40)
		public String getCpuserid() {
			return this.cpuserid;
		}

		public void setCpuserid(String cpuserid) {
			this.cpuserid = cpuserid;
		}

		@Column(name = "CPUSERNAME", length = 40)
		public String getCpusername() {
			return this.cpusername;
		}

		public void setCpusername(String cpusername) {
			this.cpusername = cpusername;
		}

		@Column(name = "THEIRCLEARINGACCOUNT", length = 40)
		public String getTheirclearingaccount() {
			return this.theirclearingaccount;
		}

		public void setTheirclearingaccount(String theirclearingaccount) {
			this.theirclearingaccount = theirclearingaccount;
		}

		@Column(name = "UNIQUEPRODUCTID", length = 56)
		public String getUniqueproductid() {
			return this.uniqueproductid;
		}

		public void setUniqueproductid(String uniqueproductid) {
			this.uniqueproductid = uniqueproductid;
		}

	}

